### ISSUE TITLE
Detail page fails to load `/#/post/:id`

### ISSUE THREAD

**Issue by labtocat** [mohandere/my-react-blog#1]
```
log.js:24 [HMR] Waiting for update signal from WDS...
checkPropTypes.js:19 Warning: Failed prop type: Invalid prop `component` of type `object` supplied to `Route`, expected `function`.
    in Route
printWarning @ checkPropTypes.js:19
index.js:19 Uncaught TypeError: Object(...) is not a function
    at Single (index.js:19)
    at mountIndeterminateComponent (react-dom.development.js:14003)
    at beginWork (react-dom.development.js:14470)
    at performUnitOfWork (react-dom.development.js:17014)
    at workLoop (react-dom.development.js:17054)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:16366)
    at renderRoot (react-dom.development.js:17148)
react-dom.development.js:15123 The above error occurred in the <Single> component:
    in Single (created by InnerLoadable)
    in InnerLoadable (created by Context.Consumer)
    in Unknown (created by ForwardRef)
    in Route
    in Switch
    in div (created by App)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Context.Consumer)
    in ConnectedRouterWithContext (created by Context.Consumer)
    in Connect(ConnectedRouterWithContext) (created by App)
    in Provider (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:15123
client:77 [WDS] Hot Module Replacement enabled.
:8082/manifest.json:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8082/manifest.json:1 Manifest: Line: 1, column: 1, Unexpected token
```

**Comment by mohandere** [comment]
Hi @labtocat 

Its working fine at my end, I am using node v11.2.0 with yarn. Please try by removing node_modules folder and reinstall it.

Can please let me your pc/node configs? Are you using npm?

![Screen Shot 2019-03-14 at 5 32 04 PM](https://user-images.githubusercontent.com/3479822/54356073-b6e91e80-4680-11e9-812c-808931e9062a.png)

**Comment by labtocat** [comment]
I tried re installing and didn't work. I am working on node `11.10.1` and using npm. seems like he have't committed all required packages. Can you cross-check and make sure you have added all dependency it in `package.json` file.

**Comment by mohandere** [comment]
Hi @labtocat 

Please pull master branch once and try removing re installing dependancies once. Before that please do -

- Remove `package-lock.json` or `yarn.lock` file.
- Remove `node_modules`
- Re install

Otherwise please try with fresh clone `https://github.com/mohandere/my-react-blog.git`

Dependancies seems correct at my end, I have on 2 pc's with fresh clone.

If issue still persist, please let me know with screenshots.


Thanks,
-Mohan

**Comment by labtocat** [comment]
@mohandere  Yup seems like your `lock` files where causing problems and now it seems to be working. I noticed you removed above mentioned files from git. Is there any reason you committed `package-lock.json` and `yarn.lock` together ?

**Comment by mohandere** [comment]
@labtocat Ideally these files should be committed to the codebase in end - so that each individual trying to run that project is doing so with exactly the tested set of dependencies. 

But unfortunately those files was committed early. 

Reference - https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494

Thanks,
-Mohan

**Comment by labtocat** [comment]
@mohandere I got the point, but why should we use `yarn` and `npm` together in the first place? Is there any specific advantage? 
Based on the walk through the app, I couldn't perform certain actions and have some doubts.
- Altho I can visually edit and delete post, the action is not reflected.ie, If I perform delete I get notification its deleted but doesn't work. Same for edit, its not getting saved.
- We have mentioned we should not use third-party packages, even when we where in call, I mentioned you can use 3rd packages but it should not affect the crud operation(correct me if you got wrong).

**Comment by mohandere** [comment]
@labtocat ok let me clarify you, Its user choice to use `yarn` or `npm`. Folks working with React usually prefers `yarn` over npm.

Also here is my clarification for your questions -

#1 - Edit/delete actions was working since beginning, but changes wasn't reflected because `jsonplaceholder.typicode.com` doesn't persisted data between calls. Now i've setup BE sever using express/mongo server and its working great(without changing `fetch` api calls)!

#2 - Building such app without external packages isn't feasible(at-least for interviews).

I suggest you to provide ready APIs to candidate for interviews(its time consuming part).

Anyway thank you for your time!

Thanks,
-Mohan
